spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  data:
    mongodb:
      username: root
      password: bucket-bingo-api
      host: host.docker.internal
      port: 27017
      database: local
      authentication-database: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://127.0.0.1:35432/bucket_bingo"
    username: "postgres"
    password: "my-first-nest-pw"
  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 33728