spring:
  data:
    mongodb:
      username: root
      password: bucket-bingo-api
      host: localhost
      port: 27017
      database: local
      authentication-database: admin

server:
  port: 33728